=== sul-dlss/folio-tasks/spec/support/schemas/mod-configuration/kv_configuration.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
    },
    "module": {
      "type": "string"
    },
    "configName": {
      "type": "string"
    },
    "code": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "default": {
      "type": "boolean"
    },
    "enabled": {
      "type": "boolean"
    },
    "value": {
      "type": "string"
    },
    "userId": {
      "type": "string"
    },
    "metadata": {
      "$ref": "../raml-util/schemas/metadata.schema",
      "readonly": true
    }
  },
  "additionalProperties": false,
  "required": [
    "module",
    "configName"
  ]
}

=== sul-dlss/folio-tasks/spec/fixtures/json/configurations/self_checkout_config.json
{
  "module": "edge-sip2",
  "configName": "selfCheckoutConfig.SERVICE_POINT_ID",
  "enabled": true,
  "value": "{\"timeoutPeriod\": 5,\"retriesAllowed\": 3,\"checkinOk\": true,\"checkoutOk\": true,\"acsRenewalPolicy\": false,\"libraryName\": \"Stanford University Libraries\",\"terminalLocation\": \"SERVICE_POINT_ID\"}"
}
